language: node_js
node_js:
- '0.10'
before_install:
- gem update --system
- gem install compass --pre
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  hipchat:
    rooms:
      secure: JYl+I5S7+OqYjn1ddmYoGJ/HFIqzrYiQzOP3qfVskp7a2eixwiWLbg9aPalIANg92MNrmv//5BshEsWxJpwadNDwVe7BNIErkmL1kvPorRBNAB04R+7mmcD4BXT8nbix5XyV9NDrad9V2A5gdHl37x3NQ2OKd+NgY/sFuH05R5o=
